version: '3.9'

# tiup playground v6.1.0 -T oss --without-monitor --db.host 0.0.0.0 --tiflash 1

services:
  data:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        BUNDLE_WITHOUT: ''
        EXECJS_RUNTIME: 'Node'
        RAILS_ENV: 'development'
        RAILS_SERVE_STATIC_FILES: 'false'
    tty: true
    stdin_open: true
    image: hooopo/ossinsight-data:latest
    restart: always

    command: ["./start.sh"]
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - DATABASE_URL=${DATABASE_URL:-tidb://root:@host.docker.internal:4000/gharchive_dev}
      - GITHUB_TOKEN=${GITHUB_TOKEN:?err}
      - SKIP_REPLICA=1

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: 'development'
    image: hooopo/ossinsight-api:latest
    restart: always
    ports: 
      - "3450:3450"
    depends_on: 
      data:
        condition: service_started
    environment:
      - DATABASE_URL=${DATABASE_URL:-tidb://root:@host.docker.internal:4000/gharchive_dev}
      - CONNECTION_LIMIT=10
      - QUEUE_LIMIT=20
      - SERVER_PORT=3450
      - GH_TOKENS=${GITHUB_TOKEN:?err}
      - PREFETCH_CONCURRENT=1
      - ENABLE_CACHE=0

  fe:
    image: hooopo/ossinsight-fe:latest
    restart: always
    build:
      context: ./web
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: 'development'
    ports: 
      - "30000:30000"
    environment:
      - NODE_ENV=development
      - APP_HOST=http://localhost:3450
      - APP_API_BASE=http://localhost:3450
    volumes:
      - web/:/app:delegated
      - web/node_modules:/app/node_modules
      - web/prefetch:/app/.prefetch
      - web/docusaurus:/app/.docusaurus

networks:
  default:

volumes:
  packs:
  node_modules:
  cache:
  bundle:
  prefetch:
  docusaurus:
