id: 10008
name: Graph Database
items:
  - neo4j/neo4j
  - arangodb/arangodb
  - geldata/gel
  - vesoft-inc/nebula
  - orientechnologies/orientdb
  - JanusGraph/janusgraph
  - RedisGraph/RedisGraph
  - cayleygraph/cayley
  - hypermodeinc/dgraph
  - terminusdb/terminusdb
  - memgraph/memgraph
  - bitnine-oss/agensgraph
  - indradb/indradb
  - surrealdb/surrealdb
  - apache/age
  - FalkorDB/FalkorDB
