id: 10087
name: LLM DevTools
items:
  - fauxpilot/fauxpilot
  - TabbyML/tabby
  - danielgross/localpilot
  - continuedev/continue
  - Aider-AI/aider
  - morph-labs/rift
  - smallcloudai/refact
  - sourcegraph/cody
  - AbanteAI/mentat
  - BloopAI/bloop
  - codefuse-ai/codefuse-chatbot
