id: 10099
name: Model Context Protocol (MCP) Client
items:
- rosaboyle/mcp-playground
- standardbeagle/mcp-tui
- evalstate/fast-agent
- EvanZhouDev/raycast-mcp
- hideya/mcp-client-langchain-py
- m-mcp/web-search
- williamvd4/mcp-client-cli
- NitroRCr/AIaW
- jiasyuanchu/mcp-chat-bot
- Toolbase-AI/toolbase
- debedb/mcp-aws
- k3d3/firefox_mcpbridge
- yonaka15/mcp-client-demo
- HazyResearch/minions
- junjiem/dify-plugin-agent-mcp_sse
- rosiefaulkner/langgraph-voice-agent
- shaoyingchen/mcp-client-llm
- wimpywarlord/mcp-react-dev-tools
- nullplatform/np-mcp-controlplane-proxy
- twwch/mcp-feishu-bot
- KokoiRuby/Kopilot-MCP
- Heminoid/mcp-voice-agent
- obrr-hhx/AskAnything
- srbhptl39/MCP-SuperAssistant
- MaitreyaM/Clap-Agents
- polymath-raval/mcp_example
- korchasa/speelka-agent
- danny-avila/LibreChat
- paulrobello/mcp_langgraph_tools
- jodobear/sparcaroo
- qu3ai/qu3-app
- shaharia-lab/mcp-frontend
- sst/opencode
- aws-samples/sample-nova-sonic-mcp
- juspay/Bedrock-MCP-Connector
- matthewhand/open-swarm
- lalanikarim/langgraph-mcp-pipeline
- MCPJam/inspector
- pickpppcc/qbittorrent-mcp
- Zeeshanunique/mcp-client
- studychain01/browser_mcp_agent
- rectalogic/pydantic-mcp
- nanbingxyz/5ire
- RegiByte/mcp-client-app
- Sakil786/airbnb_mcp
- apify/tester-mcp-client
- alessandrodorazio/mcp-client-server
- annali/HistorIQ
- deco-sites/vertex-mcp-3
- leartbeqiraj1/openai-mcp-client
- aranyak-4002/figma-design-mcp
- kamrul1157024/mcp-client
- tkellogg/tupac
- taggartbg/vibeframe
- dory-ai/n8n-mcp-bridge
- bro-in-law/mcp-demo-frontend
- swairshah/claude-cli-mcp-client
- continuedev/continue
- ananis25/mcp-client-ref
- down-to-earth1994/auto-mcp-client
- Fbeunder/MCP_FLASK
- fernandezpablo85/mcpiol
- mark3labs/mcphost
- nimishchaudhari/openhands-resolver-mcp
- supermemoryai/install-mcp
- Larkooo/dojo-mcp
- Gulp-AI/Osmosis-MCP-4B-demo
- minyang-chen/seat-booking-agent
- wong2/mcp-cli
- jinruoxinchen/mcp-web-client
- OpenAgentPlatform/Dive
- Abiorh001/omnicoreagent
- packetnomad/cursor-apple-notes-indexer
- microsoft/genaiscript
- vincent-pli/mcp-cli-host
- VikashLoomba/copilot-mcp
- dannyroosevelt/pipedream-mcp-ui
- TerminallyLazy/MCP-on-FHIR
- mihirrd/ollama-mcp-client
- viktormarinho/mcpeste
- adamdude828/claude-mcp-agent
- Sedong-Choi/unity-mcp-typescript
- paulrobello/par-mcp-inspector-tui
- chrishayuk/mcp-cli
- Cam10001110101/anthropic-mcp-connector
- aasherkamal216/Axiom
- supercorp-ai/superinterface
- tambo-ai/tambo
- saqadri/mcp_agent_streamlit_rag
- bytedance/UI-TARS-desktop
- kuzushilabsorg/mcp-clients
- Dicklesworthstone/ultimate_mcp_client
- danbri/xmcp-foaf
- csonigo/slack-mcp-client
- danieloh30/quarkus-agentic-mcp
- justinhuang0208/launchbar-mcp_agent
- getjavelin/ramparts
- arenoth/mcp-agent
- Kiran1689/algolia-mcp-client
- zinja-coder/zin-mcp-client
- swairshah/term-mcp-client
- director-run/director
- TeamSparkAI/teamspark-workbench
- 3choff/mcp-chatbot
- CopilotKit/mcp-client
- yashwant1810/Splunk-MCP-Multi-Agent-System
- block/goose
- Lucassssss/eechat
- jmand626/NASAApi-Connector
- modelcontextprotocol/inspector
- GongRzhe/Open-MCP-Client
- ggozad/oterm
- hideya/mcp-client-langchain-ts
- adafap/api-mcp
- langchain-ai/langchainjs-mcp-adapters
- truffle-ai/dexto
- wuaodi/SpaceMind
- cpage-pivotal/cf-mcp-client
- justjoehere/mcp_gradio_client
- michaeldslim/mcp-notion-api
- namank5x/kiters-mcp-client
- shawn996/mcp_ha_xiaozhi
- difybase/dify-connect-mcp
- alishangtian/proteus-ai
- cloudwalk/hermes-mcp
- bigmb/mb_mcp
- hideya/langchain-mcp-tools-ts-usage
- adhikasp/mcp-client-cli
- kicker315/deepseek_qgis_mcp
- mario-andreschak/FLUJO
- navneet-ag/cursor-jira-mcp
- seekrays/seekchat
- Zovi343/oai_mcp_code_agent
- ThingsPanel/thingspanel-mcp
- xark-argo/argo
- leehack/flutter-mcp-ai-chat
- albertvillanova/tinyagents
- FabriBorgobello/chat-mcp-rag
- edanyal/mcp-client
- Compiler-Inc/SwiftMCP
- yoheimuta/protolint
- extopico/llama-server_mcp_proxy
- Cloud-Thinker-AI/mcp-manager
- Ejb503/multimodal-mcp-client
- Kin-10/MCP_LLM
- funwarioisii/sample-mcp-rails
- IMNMV/ClaudeR
- MichaelMoriarty67/mcp-autogen
- milind-soni/MCP
- pawankumar94/Jira_mcp_streamlit
- platinum-hill/cobolt
- Robert-GitHubUserName/WinFormsApp-MCP
- RooseveltAdvisors/fastapi-mcp-client
- SettledCo/MCP-for-Laravel
- blacsheep/LLM-Amap-mcp
- Parham-dev/ai-agent-cs
- CursorTouch/MCP-Agent
- utkucy/arbitrum-mcp-tools
- Nikunj2003/LLaMa-MCP-Streamlit
- akktrsst/MCP_Agent_Airbnb
- craigsdennis/openai-responses-mcp-client-enabled
- umuo/hot-topic-mcp
- zaidmukaddam/scira-mcp-chat
- LSTM-Kirigaya/openmcp-client
- developit/mcp-cmd
- scriptoshi/laravel-mcp-client
- cognitivecomputations/dolphin-mcp
- CherryHQ/cherry-studio
- Sansan4ez/mcp-cli
- machaojin1917939763/mcp-ui
- Intelligent-Systems-Lab/mcp_client_ollama
- Fbeunder/MCP_CLI_CLIENT
- mshojaei77/EasyMCP
- JiamingHuangHJM/zsh_chatbot_mcp
- shane-kercheval/mcp-client-agent
- evilsocket/nerve
- EvolutionAPI/evo-ai
- kabrony/claude-agent-mcp
- Klavis-AI/klavis
- Study944/AI-Agent-Zxc
- mashriram/mcp_client_local
- sparktsao/mcp_meet_agentiq
- byeblack/wasi_mcp_client
- CopilotKit/open-mcp-client
- ezyang/codemcp
- mizakaHK/mcp-gomamayo
- ahmedrowaihi/webcontainer-mcp-browser
- lingster/mcp-llm
- chunkydotdev/bldbl-mcp
- mrgoonie/langgraph-multiagent-boilerplate
- menloresearch/jan
- richardanaya/UtilityBelt
- xprilion/genkit-mcp-client-blender
- xkzy/vscode-mcp-rag
- toberyan/deepin-mcp
- buyitsydney/CodingBaby-Browser-MCP
- coldielb/blnk
- inventorado/Ollamaton
- emredeveloper/MCP-Turkey-Weather
- tim-schultz/mcp-client-rs
- gnosis23/tiny-mcp-client
- google-gemini/gemini-cli
- sidharthrajaram/mcp-sse
- garvk/mcp-postgresql-agent-hack
- jagan-shanmugam/mattermost-mcp-host
- AstraBert/TySVA
- macuse-app/macuse
- tony-nexartis/anthropic_mcp_hackathon_sse_client
- RGGH/mcp-python-client
- OmChillure/mcpui
- mctrinh/mcp-chatbot
- wxhzhwxhzh/DrissionPageMCP
- ThinkInAIXYZ/deepchat
- keta1930/mcp-agent-graph
- slavashvets/mcp-http-client-example
- ellieli0630/langgraph-mcp-agent-twitter
- microsoft/vscode
- c1pher-cn/ha-xiaozhi-mcp
- ShwStone/mcp-oi-wiki
- itisaevalex/mistr-agent
- MauroStyleman/KAFRMA-Backend
- fkesheh/mcp-ai-agent
- HiCoderMonkey/agents-mcp-cloud
- tahtaciburak/calmcp
- ashishpatel26/SmolAgentWithMCP
- huggingface/smolagents
- kirintea/MCP_Modularity
- yeakub108/mcp-client
- setkyar/claude-mcp
- BigSweetPotatoStudio/hyper-mcp-terminal
- daodao97/chatmcp
- hatasaki/azure-mcp-cli-client
- nerding-io/n8n-nodes-mcp
- nicozumarraga/light-mcp-agents
- shahshrey/universal-mcp-ui
- keli-wen/mcp_chatbot
- shuakami/mcp-download
- ibelick/zola
- dshivendra/crewai_mcp_adapter
- nachoal/react-agent-with-mcp
- DenizAkansoy/MCPHack
- cline/cline
- runebookai/tome
- YashMakan/flutter_mcp
- nbonamy/witsy
- netixc/speech-mcp
- ACNet-AI/OmniTaskAgent
- kkul-eng/mcp-claude-demo
- hjlarry/dify-plugin-mcp_agent
- jobsonlook/xhs-mcp
- techspawn/Turbo-MCP-Client
- jlmelis/mcp-proving-ground-client
- tarasyarema/prodex-js
- mediar-ai/MCP-server-client-computer-use-ai-sdk
- purunep/streamble-http-mcp-client
- S-k-Srivastava/mcp-math-solver
- l145dev/Google-Maps-MCP-Speech
- Xingsandesu/CarrotAI
- cursor/cursor
- gcc3/simple-ai-chat
- Destiner/oneshot
- AnyContext-ai/remote-mcp-chat
- sooperset/mcp-client-slackbot
- ateeyak/n8n-nodes-mcp
- box-community/box-mcp-pydantic-ai
- ChatGPTNextWeb/NextChat
- John-Lin/agentic-slackbot
- amidabuddha/console-chat-gpt
- aswincandra/fast-mcp-client
- karthikv2k/chat-mcp
- mastra-ai/discord-mcp-bot
- i2y/langchaingo-mcp-adapter
- binarybana/easyrag
- Chainlit/chainlit
- GH05TCREW/PentestAgent
- wrediam/n8n-coolify-mcp-tools
- GeLi2001/mcp-terminal
- rakesh-eltropy/mcp-client
- MdHelalUddinBiswas/Open-Mcp-Client
- rairai77/weather-tool-with-mcp
- autometa-dev/whatsapp-mcp-voice-agent
- duke7able/gemini-mcp-desktop-client
- shren207/weather-mcp
- kartikeyapandey20/mcp-client
- RGGH/refactored-octo-parakeet
- RussellLuo/cmcp
- faraazahmad/mcp_debug
- luohy15/y-cli
- georgi-terziyski/mcp_client_ollama
- WinterTechForum/MCP-demo
- zed-industries/zed
- nick1udwig/kibitz
- runekaagaard/aterm2
- crayon3shawn/mcp-cli-manager
- aws/amazon-q-developer-cli
- BigSweetPotatoStudio/HyperChat
- RooCodeInc/Roo-Code
- mcp-use/mcp-use
- dictybase-docker/mcphost
- groq/groq-desktop-beta
