id: 10103
name: Mocking and Stubbing tools
items:
  - mock-server/mockserver 
  - keploy/keploy
  - wiremock/wiremock
  - mockoon/mockoon
  - SpectoLabs/hoverfly 
  - mountebank-testing/mountebank
  - requestly/requestly 
  - uber-go/mock
  - microcks/microcks
